#!/bin/bash

# enable debug mode
if [ "$DEBUG" = "yes" ]; then
	set -x
fi

# Setup the CURRENT_DIR for different operating systems.
case $(uname -s) in
Linux)
	export CURRENT_DIR=$(dirname "$(readlink -e "$0")")
	;;
FreeBSD|OpenBSD|NetBSD)
	export FLAGS_GETOPT_CMD='/usr/local/bin/getopt'
	export CURRENT_DIR=$(dirname "$(realpath "$0")")
	;;
Darwin) # MacOS
	PRG="$0"
	while [ -h "$PRG" ]; do
		link=$(readlink "$PRG")
		if expr "$link" : '/.*' > /dev/null; then
			PRG="$link"
		else
			PRG="$(dirname "$PRG")/$link"
		fi
	done
	export CURRENT_DIR=$(dirname "$PRG")
	;;
*MINGW*)
	export CURRENT_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
	pwd () {
		builtin pwd -W
	}
	;;
*)
	# The sed expression here replaces all backslashes by forward slashes.
	# This helps our Windows users, while not bothering our Unix users.)
	export CURRENT_DIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
	;;
esac

usage() {
	echo "usage: gitflow <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "feature     Manage your feature branches."
}

main() {
	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

	# Load environment variables
	. "$CURRENT_DIR/.env"

	# Use the shFlags project to parse the command line arguments
	. "$CURRENT_DIR/shFlags"
	FLAGS_PARENT="./feature"

	# Load common functionality
	. "$CURRENT_DIR/common"

	# allow user to request git action logging
	DEFINE_boolean 'showcommands' false 'Show actions taken (git commands)'
	# but if the user prefers that the logging is always on,
	# use the environmental variables.
	gitflow_override_flag_boolean 'showcommands' 'showcommands'

	SUBCOMMAND="$1"; shift

	if [ ! -e "$CURRENT_DIR/cmd-$SUBCOMMAND" ]; then
		usage
		exit 1
	fi

	# Run command
	# . == source command --> Incorporate source file into current shell 
	. "$CURRENT_DIR/cmd-$SUBCOMMAND"
	FLAGS_PARENT="./gitflow $SUBCOMMAND"

	if [ -z "${SUBACTION}" ]; then
		# If the first argument is a flag, it starts with '-', we interpret this
		# argument as a flag for the default command.
		if startswith "$1" "-"; then
			SUBACTION="default"
		elif [ -z "$1" ]; then
			SUBACTION="default"
		else
			SUBACTION="$1"
			shift
			# Do not allow direct calls to subactions with an underscore.
			if $(contains "$SUBACTION" "_"); then
				warn "Unknown subcommand: '$SUBACTION'"
				usage
				exit 1
			fi
			# Replace the dash with an underscore as bash doesn't allow a dash
			# in the function name.
			SUBACTION=$(echo "$SUBACTION" |tr '-' '_')
		fi
	fi

	if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
		warn "Unknown subcommand: '$SUBACTION'"
		usage
		exit 1
	fi

	# Run the specified action
	if [ $SUBACTION != "help" ] && [ $SUBCOMMAND != "init" ]; then
		initialize
	fi
	if [ $SUBACTION != 'default' ]; then
		FLAGS_PARENT="./gitflow $SUBCOMMAND $SUBACTION"
	fi

	cmd_$SUBACTION "$@" "${_short_branch_name}"
}
main "$@"